### ISSUE TITLE
Move back to top button to right

### ISSUE THREAD

**Issue by Jamjarman** [jonfroehlich/makeabilitylabwebsite#116]
Jon, you had mentioned moving the back to top button to the right, was that for all screen sizes or just for mobile?

**Comment by jonfroehlich** [comment]
Following up on this. I think a smaller button overall and one on right side of screen might be better.

Like this (from http://oshinewptheme.com/v1/):

![image](https://user-images.githubusercontent.com/1621749/32128411-499893cc-bb32-11e7-882d-c5faebd7a395.png)

**Comment by jonfroehlich** [comment]
I completely removed the back-to-top button functionality for now. We can revisit if this functionality gets reintroduced.
