### ISSUE TITLE
Front Page Design: empty space at the bottom

### ISSUE THREAD

**Issue by myjeeed** [jonfroehlich/makeabilitylabwebsite#191]
I think we can reduce the number of tweets that we're showing so that we could get rid of this empty space below "Recent Talks"

![image](https://cloud.githubusercontent.com/assets/9346800/19120382/98533724-8af0-11e6-9da3-a21b14e6f317.png)

**Comment by jonfroehlich** [comment]
This refers to the old landing page, which has now been redesigned.
