### ISSUE TITLE
Front Page Icons: acknowledge or purchase

### ISSUE THREAD

**Issue by myjeeed** [jonfroehlich/makeabilitylabwebsite#195]
I got these icons from [TheNounProject](thenounproject.com) and we need to either purchase them or acknowledge the designers!

![image](https://cloud.githubusercontent.com/assets/9346800/19121074/1ddfedea-8af3-11e6-9f4d-db28a22a93c8.png)

I will update this post with the links to the icons soon!

**Comment by jonfroehlich** [comment]
We are no longer using these icons, so closing for now.
