### ISSUE TITLE
Cron needs new owner

### ISSUE THREAD

**Issue by Jamjarman** [jonfroehlich/makeabilitylabwebsite#199]
I used to have a cron running on the server (utilities/LogParser/parse.sh which gets the recently viewed pubs and talks from the access logs. All you need to do is add 

`00 * * * * cd /srv/makeabilitylab/utilities/LogParser/ && ./parse.sh`

To your crontab (`crontab -e`)

I also no longer have access to the directory the logs are in (`/var/log/httpd/`) So you will probably need to get in touch with UMIACS about that as well. 

I'm going to shut my version of the cron off as it's not working until the access to that directory is restored and I'm getting failure emails.

**Comment by jonfroehlich** [comment]
Not doing cron anymore so closing
