### ISSUE TITLE
Project Page People Listing: Title (e.g., Undergraduate) seems to show Oldest First instead of Most Recent

### ISSUE THREAD

**Issue by mattm401** [jonfroehlich/makeabilitylabwebsite#216]
![image](https://cloud.githubusercontent.com/assets/1121334/21366834/8b4a39be-c6c9-11e6-9783-40569a7abf6d.png)

Here you can see Jonah and Jamie both still register as "High School Student" despite having newer status/roles as "Undergrad" assigned to them.

**Comment by jonfroehlich** [comment]
Fixed.
