### ISSUE TITLE
NaN publication year on Firefox

### ISSUE THREAD

**Issue by misaugstad** [jonfroehlich/makeabilitylabwebsite#242]
I have noticed on Firefox that many of the publications on the site have "NaN" as their year of publication. I do not see this behaviour on Chrome, however.

![nan_pubs](https://cloud.githubusercontent.com/assets/6518824/26594704/a9542776-4536-11e7-8177-9dd041b2c877.png)

**Comment by jonfroehlich** [comment]
No longer appears to be a problem.

![image](https://user-images.githubusercontent.com/1621749/69747411-30d01380-10fb-11ea-838a-52269e405197.png)
