### ISSUE TITLE
Landing Page: News item image is not linked to the news article

### ISSUE THREAD

**Issue by manaswis** [jonfroehlich/makeabilitylabwebsite#244]
Currently, the news image links to the home page. Ideally, it should link to the associated news article.

![image](https://cloud.githubusercontent.com/assets/2873216/26640732/87d64d3e-45f6-11e7-8c6e-54ad50339179.png)

**Comment by jonfroehlich** [comment]
We got rid of these news feed on landing page, so closing Issue.
