### ISSUE TITLE
People Sub-Page: Potential Image Overlap

### ISSUE THREAD

**Issue by mattm401** [jonfroehlich/makeabilitylabwebsite#245]
If you view Teja's sub page from the people page, his easter egg isn't properly sized with the actual photo:

![image](https://cloud.githubusercontent.com/assets/1121334/26641572/063baabe-45f9-11e7-85a0-c7447ac1376d.png)

**Comment by jonfroehlich** [comment]
This has been addressed:

![image](https://user-images.githubusercontent.com/1621749/69747812-e7cc8f00-10fb-11ea-977a-958da9cc6d80.png)
