### ISSUE TITLE
Talk Page Does Not Show Talk Venue

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#251]
The talk location is emphasized rather than the venue. For example, the CHI talks are shown as Denver, Colorado but not as CHI'17 talks:

![image](https://user-images.githubusercontent.com/1621749/26959024-f29125d0-4c9b-11e7-8fe6-d360226f538f.png)

**Comment by jonfroehlich** [comment]
This is fixed on the landing page: 

![image](https://user-images.githubusercontent.com/1621749/41747417-cffe4d4a-7562-11e8-8726-42a8135387ca.png)

Indeed, to reduce code redundancy, perhaps this should be rendered from a common function, if possible? Otherwise, relevant code could likely be copy/pasted from landing page.

**Comment by johnsonkuang** [comment]
Error is in the script that loads the data from django into JSON, should be talk.forum_name, is listed as talk.location

**Comment by jonfroehlich** [comment]
This is now fixed (using a snippet).

![image](https://user-images.githubusercontent.com/1621749/69589031-695ada80-0f9f-11ea-8f4a-525638dc2458.png)
