### ISSUE TITLE
Check To See When We Delete a File Like a Talk or Paper That the File is Actually Removed from File Storage

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#257]
That the file is actually removed from file storage

**Comment by jonfroehlich** [comment]
I don't think it is. We should do this to save space on our server.

**Comment by johnsonkuang** [comment]
What do you mean be delete a file? As in clearing it on the admin but keeping the object, or deleting the object entirely. @jonfroehlich

**Comment by jonfroehlich** [comment]
I mean that we delete it in admin page but the file in /media is not actually removed.

**Comment by johnsonkuang** [comment]
So you want to delete it when you delete the object on the admin

**Comment by jonfroehlich** [comment]
That's right. Sorry that this was unclear. If you read the title of the post along with the text of the first post, it should read like "Check to see that when we delete a file like a talk or a paper, that the file is actually removed from storage."

Basically, I don't want a whole bunch of deleted files taking up storage on the web server.

**Comment by johnsonkuang** [comment]
already on it

**Comment by johnsonkuang** [comment]
PR merged closing Issue
