### ISSUE TITLE
Footer needs to be polished

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#26]
Among other things, the logos are not vertically aligned properly:
![image](https://cloud.githubusercontent.com/assets/1621749/15271506/0e0af254-1a1c-11e6-85e9-a5200ad277f3.png)

We should also discuss what other things we might want in the logo and whether we are happy with the current aesthetic.

**Comment by jonfroehlich** [comment]
This is in process. Still needs to be refined a bit... In particular, the column spacing feels a bit off but overall, I think this is almost done.

![image](https://user-images.githubusercontent.com/1621749/34090584-fb153be8-e36c-11e7-9230-6e9ee98a92d4.png)

**Comment by jonfroehlich** [comment]
I just noticed in @higherdefender's screenshot that he shared over email that the footer does not look good (at all) at larger widths (e.g., with bigger monitors or different resolutions). So we need to fix that too.

**Comment by EdigaHe** [comment]
<img width="1279" alt="screen shot 2017-12-18 at 2 12 21 pm" src="https://user-images.githubusercontent.com/3831526/34130681-a0957840-e3fd-11e7-8c2b-2bcb4d0d43fd.png">

I redesigned the layout of the footer. It is not responsive yet for all kinds of screens/devices/resolutions as @jonfroehlich and @higherdefender mentioned. I'm working to resolve this issue.

**Comment by jonfroehlich** [comment]
Please create another issue that is about the responsiveness of the footer.

**Comment by jonfroehlich** [comment]
Addressed in https://github.com/jonfroehlich/makeabilitylabwebsite/pull/330
