### ISSUE TITLE
Bug in Past Project Members

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#260]
Ryan Holland hasn't even started yet but is listed as a past project member on the Project Sidewalk projects page:

![image](https://user-images.githubusercontent.com/1621749/27265558-bc80c4ec-5465-11e7-8c95-b69b779de1cb.png)

**Comment by jonfroehlich** [comment]
@aileenzeng, didn't you work on something similar?

**Comment by aileenzeng** [comment]
@jonfroehlich Yeah -- I think this could be related to issue #262. I think I fixed one of the calculations in the database that made future members display as active. I'm not sure there's a way that we're differentiating between inactive past members/inactive future members. I can look into this more soon.

**Comment by jonfroehlich** [comment]
Thanks. :)
