### ISSUE TITLE
Publications with future dates don't show up in publications page

### ISSUE THREAD

**Issue by lstearns86** [jonfroehlich/makeabilitylabwebsite#264]
I thought that they used to show up and be marked "To Appear". Was this changed intentionally or is it broken?

**Comment by jonfroehlich** [comment]
This is not the intended behavior. They should show up and be marked _To Appear_.

**Comment by jonfroehlich** [comment]
Is this for the individual project page or for the publications page?

**Comment by lstearns86** [comment]
They don't show up at all on the main publications page, and while they do
show up on the index and individual project pages they are not marked "To
Appear".
