### ISSUE TITLE
Acceptance rates on individual project page not truncated

### ISSUE THREAD

**Issue by lstearns86** [jonfroehlich/makeabilitylabwebsite#265]
They should be truncated or rounded as done on the main publications page

**Comment by jonfroehlich** [comment]
Please add screenshot.

**Comment by lstearns86** [comment]
![image](https://user-images.githubusercontent.com/2319490/31741438-3df8cb02-b422-11e7-8589-f673b9869b0c.png)

Looks like it's also not multiplying by 100 to convert into percentages.

**Comment by jonfroehlich** [comment]
Aahahaha. Yikes!
