### ISSUE TITLE
Move Dev Environment to Docker

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#266]
UW Paul Allen uses Docker for everything so setup dev environment for that and update documentation accordingly.

**Comment by jonfroehlich** [comment]
Starting to record notes about this in our [dev notes Google Doc](https://docs.google.com/document/d/149S_SHOzkJOhNHU4ENMU0YCbk-Vy92y5ZSTeCXG9Bhc/edit#heading=h.gjdgxs) (password protected). Looks like there are lots of ways to approach this and, unfortunately, no standard "easy" way...

**Comment by jonfroehlich** [comment]
@aileenzeng, we now have comprehensive notes on this in the readme.md, right? So, I think this can be closed... thoughts?

**Comment by aileenzeng** [comment]
@jonfroehlich Yup! :)
