### ISSUE TITLE
Filter Bar Overlaps with Footer On Scroll

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#286]
When you scroll down far enough, the filter bar overlaps with the footer. This affects publications, projects, videos, talks, etc.

As a possible solution, could we push the z-index of the filter bar down so that it slides under the footer?

![image](https://user-images.githubusercontent.com/1621749/33295681-ebbb01c8-d38b-11e7-8cc8-9aff39acadf2.png)

**Comment by misaugstad** [comment]
So the filter was stacked on top of the footer b/c the footer wasn't positioned (while the filters are). I set `position: relative` for the footer, and now it is stacked on top of the filters.

Here are before/after GIFs for the publications page:
![footer-old](https://user-images.githubusercontent.com/6518824/34127741-3071cf6e-e40c-11e7-91ac-a6b128fcae75.gif)
![footer-new](https://user-images.githubusercontent.com/6518824/34127659-ee1fe68c-e40b-11e7-9884-a9b660d952fe.gif)

And here is a look when we are more zoomed.
![footer-old-2](https://user-images.githubusercontent.com/6518824/34127742-3095c7c0-e40c-11e7-85cd-32e37665ef21.gif)
![footer-new-2](https://user-images.githubusercontent.com/6518824/34127740-305ebeba-e40c-11e7-9de6-d2264d9b06f8.gif)

**Comment by jonfroehlich** [comment]
Looks great! Submit a PR.
