### ISSUE TITLE
Mouseover/Hover Effect for Artifact Thumbnails

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#287]
I quite like the following subtle hover effect that has become common on portfolio pages: you mouseover a thumbnail and it zooms the image (and sometimes does a slight darkening + text overlay).

See https://www.awwwards.com/websites/portfolio/ & vanschneider.com for demos of this effect.

Looks pretty easy to implement. My suggestion would be to have a css class like artifact-thumbnail-hover or something that can be used on *any* artifact thumbnail that we want like project thumbnails, talk thumbnails, paper thumbnails, etc.

**Comment by jonfroehlich** [comment]
I think this might be a good one for @lstearns86 to start with for Hackathon.

**Comment by lstearns86** [comment]
Here's an example of the new behavior:

![image](https://user-images.githubusercontent.com/2319490/34125641-fa748ce6-e404-11e7-8fe0-2a1622d44360.png)

You can add the class artifact-thumbnail-hover to any element that contains an image and it will zoom 20% on hover. I also added the artifact-overlay class which will add the dark overlay and the artifact-overlay-content class which sets the text and link color to white and positions it in the bottom left of the container.

**Comment by jonfroehlich** [comment]
Can you try:
- Increasing the font size
- Vertically and horizontally centering text
- Consider putting white rectangle (with rounded corners) around each text (e.g., to convey button and clickability)

**Comment by lstearns86** [comment]
Updated overlay link styles:

![image](https://user-images.githubusercontent.com/2319490/34127158-16660fb0-e40a-11e7-8cd4-af4aa71ef96b.png)

Or if there are too many for a single line (also showing link hover behavior):

![image](https://user-images.githubusercontent.com/2319490/34127184-27df8b72-e40a-11e7-97d0-9de02b5450ef.png)

How's that? Also, I assume that I should remove the redundant links below?

**Comment by jonfroehlich** [comment]
- More vertical and horizontal margin in each button
- No need to have opacity in button. Just make mouseover opacity for whole thumbnail dark enough that it is easy to read button text. Can you find some examples of this style of mouseover online and post them into this thread?
- What font are you using?

**Comment by lstearns86** [comment]
Do you mean the padding within the button (separating from the border)? Or the separation between the buttons?

I can keep looking, but I couldn't quickly find any examples that have the behavior you want. The [link](https://www.awwwards.com/websites/portfolio/) you provided initially is the closest I saw, with the arrow link in the bottom right.

I'm using the default font that we're using for text pretty much everywhere else.

**Comment by lstearns86** [comment]
How's this?

![image](https://user-images.githubusercontent.com/2319490/34127734-2a3ce1e2-e40c-11e7-8ff0-865f39c800fd.png)

I increased the internal padding, got rid of the button background colors, and increased the overlay darkness to make the buttons more readable for light colored images.

**Comment by jonfroehlich** [comment]
Fixed in https://github.com/jonfroehlich/makeabilitylabwebsite/pull/325
