### ISSUE TITLE
Landing page category icons need to be highlighted on mouseenter

### ISSUE THREAD

**Issue by higherdefender** [jonfroehlich/makeabilitylabwebsite#293]
![image](https://user-images.githubusercontent.com/11636527/33507464-ba3a397c-d6a9-11e7-99a0-17ce86802e04.png)
These icons need to be highlighted (color changed, enlarged, etc.) on cursor enter. It's hard to know if they are links.

**Comment by jonfroehlich** [comment]
Those are gone.
