### ISSUE TITLE
Consistent Margins

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#301]
The landing page currently has two different content margins (as captured by the screenshot below--the blue line and the red line). We should have only one margin for consistency but need to choose which one we like best: red or blue. 

![image](https://user-images.githubusercontent.com/1621749/33786101-a4d9776e-dc1c-11e7-9e6d-e88e8b369041.png)

**Comment by higherdefender** [comment]
I vote for red  - it's more compact and relevant. But, I also don't want to have a lot of whitespace between the website margin and the browser window margin.

**Comment by jonfroehlich** [comment]
Thanks @higherdefender. What do others think?

**Comment by misaugstad** [comment]
I think the question of whitespace is the important question. Am I correct in thinking that on a typical laptop screen, at the default zoom level, there would be quite a bit of whitespace in the margins for the red? If so, then I'd vote for blue, o/w red.

**Comment by higherdefender** [comment]
+1 mikey.

Pax vobiscum,
dhruvjain.info

Good emailing strategies, please read this
<http://thinksimplenow.com/productivity/15-tips-for-writing-effective-email/>
.

**Comment by jonfroehlich** [comment]
@johnsonkuang, you are currently working on this so assigning you.

**Comment by jonfroehlich** [comment]
@ShivenBhatt, I tried to make the content-div 1400px for the landing page. See `.makelab-content-container` in index.css but I must have messed it up because the page is not rendering correctly. Can you take a look and fix it?

The Recent Projects and Recent Videos part looks OK when I fullscreen my browser but the other sections are broken. 

![image](https://user-images.githubusercontent.com/1621749/43289766-d208f588-90e0-11e8-8c8f-5adee60cc228.png)

Broken parts including the footer:
![image](https://user-images.githubusercontent.com/1621749/43289810-f5b79098-90e0-11e8-8c4d-07af99246765.png)

**Comment by jonfroehlich** [comment]
Can we please fix this? I had originally assigned @johnsonkuang and it didn't get done. Then I assigned @ShivenBhatt and I haven't seen any progress. So, please prioritize this and https://github.com/jonfroehlich/makeabilitylabwebsite/issues/505 (which are related).

**Comment by ShivenBhatt** [comment]
@jonfroehlich, fixed, pull request is at #514.
