### ISSUE TITLE
Consider 6, 7, or even 8 People Per Row for Project Pages

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#303]
Rather than 5.

With 5, images feel too big...

**Comment by jonfroehlich** [comment]
Whoever works on this should try 5,6,7, and 8 and screenshot each layout below and then we can vote on what we like better. :)

**Comment by alexjk38** [comment]
5 People per row:
<img width="1440" alt="5blocks image" src="https://user-images.githubusercontent.com/32470028/42364430-fbd78e42-80af-11e8-8ba9-355197215775.png">
6 People per row:
<img width="1440" alt="6people image lg-2" src="https://user-images.githubusercontent.com/32470028/42364433-fd7bdb72-80af-11e8-8d97-d097a2499eff.png">
7 People per row:
<img width="1440" alt="7people image" src="https://user-images.githubusercontent.com/32470028/42364560-66c4b194-80b0-11e8-9bb6-5ed89bc18bdc.png">
8 People per row:
<img width="1440" alt="8people image" src="https://user-images.githubusercontent.com/32470028/42364573-6e686d46-80b0-11e8-8df1-4f0145e908e2.png">

**Comment by jonfroehlich** [comment]
Nice progress Alex! Can you use our actual face shots? Hard to get a sense of how this will look when you’re not even using headshots.

**Comment by alexjk38** [comment]
Updated with Headshots - 
5 people:
<img width="1440" alt="5people image" src="https://user-images.githubusercontent.com/32470028/42403985-3eca3648-813a-11e8-972c-05442c1888ac.png">
6 people:
<img width="1440" alt="6people image" src="https://user-images.githubusercontent.com/32470028/42403991-46cc25a4-813a-11e8-9ec9-74db2220eda3.png">
7 people:
<img width="1440" alt="7people image" src="https://user-images.githubusercontent.com/32470028/42403994-4ca6457c-813a-11e8-9e1f-62a47f8f94a8.png">
8 people:
<img width="1440" alt="8people image" src="https://user-images.githubusercontent.com/32470028/42403995-52927c12-813a-11e8-8660-78d2870fe0ed.png">

**Comment by jonfroehlich** [comment]
I think I like six best (though to properly evaluate 7 and 8, you'd have to change the CSS beneath the images to better match the available width--e.g., by reducing font sizes).

@aileenzeng, @EdigaHe, and @higherdefender: what's your preference?

**Comment by aileenzeng** [comment]
I like 5 slightly better than 6, but I think both of them are nice! I think if we do end up doing 6, we still might need to reduce the font size (University of Washington might cause some overflow with the current size?)

**Comment by higherdefender** [comment]
For me: If we can fill the second row in 6 so that the display covers more
than 50% of the width most of the time, then 6. Otherwise, 5.

Pax vobiscum,
dhruvjain.info

Good emailing strategies, please read this
<http://thinksimplenow.com/productivity/15-tips-for-writing-effective-email/>
.

**Comment by jonfroehlich** [comment]
Keeping five for now.

![image](https://user-images.githubusercontent.com/1621749/69588983-3fa1b380-0f9f-11ea-842a-b23ca3d72114.png)
