### ISSUE TITLE
Some Visited Links Are White

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#309]
I'm not sure why this is because I thought this css was only relevant for content within a div marked as .makelab-footer-col as I have:

```
.makelab-footer-col a:link, a:visited {
	color: white;
}
```
I thought this meant that the a:link and a:visited style was only relevant with divs within makelab-footer-col. However, visited links are showing up as white everywhere... so maybe I'm misunderstanding something fundamental about CSS:

![image](https://user-images.githubusercontent.com/1621749/34065108-a93739b2-e1b3-11e7-8013-952fbc90516f.png)

**Comment by jonfroehlich** [comment]
@lstearns86 Do you understand what's going on here? Am I misunderstanding how css works somehow?

**Comment by lstearns86** [comment]
I think that you need to specify the container class on both sides of the comma. That’s why all of the visited links are showing up white, it’s matching all a:visited elements.

E.g., https://www.sitepoint.com/community/t/whats-the-difference-between-comma-separated-identifiers-and-space-separated/6309/2

**Comment by jonfroehlich** [comment]
That fixed it. Thanks!
