### ISSUE TITLE
API for Pubs, Talks, Etc.

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#311]
I want to stop updating my personal webpage and, instead, pull content dynamically from the Django site. This will be far more manageable for me as I won't have to keep two websites up-to-date. (One reason I still need a pubs listing on my personal site is that we decided, as a group, for the ML pubs listing to only go back to 2012, so it doesn't capture all of my pubs back to 2004--even though those are stored in Django database).

**Comment by johnsonkuang** [comment]
API created and merged, closing issue

**Comment by jonfroehlich** [comment]
@johnsonkuang, do you have any documentation for how to use the API? I want to use it for my website (as noted above) and will start testing it when I dev on it.

**Comment by johnsonkuang** [comment]
[Makelab REST API.docx](https://github.com/jonfroehlich/makeabilitylabwebsite/files/2276000/Makelab.REST.API.docx)

@jonfroehlich see attached document for complete documentation
