### ISSUE TITLE
Mouseover Talk Thumbnail and Show PDF | PPTX Download Options

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#313]
When you mouseover talk thumbnail, have the thumbnail go dark (with opacity layer) and show PDF | PPTX overlaid text as download options.

![image](https://user-images.githubusercontent.com/1621749/34076797-4850ccdc-e2a6-11e7-86bf-8ff230e749ec.png)

**Comment by jonfroehlich** [comment]
This is related to https://github.com/jonfroehlich/makeabilitylabwebsite/issues/287. Assigning @lstearns86 as he will be addressing both simultaneously.

**Comment by lstearns86** [comment]
Added in #325

**Comment by jonfroehlich** [comment]
@lstearns86 added the functionality for this in pull request https://github.com/jonfroehlich/makeabilitylabwebsite/pull/325 (now merged into master); however, this is still not hooked up. So, I don't want to close this Issue until it's hooked up on landing page and talks.html page. Unassigned @lstearns86 for now so he can work on his other assigned hackathon issues.

**Comment by jonfroehlich** [comment]
OK, looks like it's implemented on talks.html but not landing page. Fine. We can create another issue for landing page.

However, before we close this, I think that when there is only one link in the thumbnail, that the entire thumbnail should be clickable not just the button. So the behavior should be like: https://www.awwwards.com/websites/portfolio/. I realize this is not possible if two or more buttons are overlaid as clicking outside the button in that case is ambiguous.

![image](https://user-images.githubusercontent.com/1621749/34128522-dca0e692-e3f5-11e7-8e26-995f19f8bbda.png)

**Comment by jonfroehlich** [comment]
We now have pop-up links that come up below the thumbnail (e.g., see HandSight thumbnail below), which seems to work well for now. So, closing this.

![image](https://user-images.githubusercontent.com/1621749/70540433-185bf200-1b1a-11ea-84cc-762367a0e4c4.png)
