### ISSUE TITLE
Update Talks Page to Mimic Formatting on Landing Page

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#314]
I updated the way we handle talks and the presentation of thumbnails, the text below the thumbnails, etc. on the landing page. These modifications need to be incorporated into the talks.html page.

**Comment by jonfroehlich** [comment]
Now that you're working on this @SeokbinKang, note that I do *not* want explicit download links below the thumbnails (as we currently have). Instead, I think we should try just using @lstearns86's new hover code that overlays links on thumbnail on mouseover. We can try that and see if we like it. If we don't, then we can add in an additional download links line.

**Comment by SeokbinKang** [comment]
[Before]
<img width="589" alt="before314" src="https://user-images.githubusercontent.com/10859410/34133046-972c1480-e407-11e7-82e4-58267f20d7b0.png">

[After]
<img width="581" alt="after314" src="https://user-images.githubusercontent.com/10859410/34133051-a1d6315e-e407-11e7-831b-d398fb1ee46c.png">

**Comment by jonfroehlich** [comment]
This doesn't look like the landing page. What's with the vertical space between thumbnail and title, for example? See screenshot below. Since I wrote the code for the landing page, I'm happy to quickly work on this one. I don't think it should take much effort... you basically just have to follow the talk code that I wrote for landing page... Also, you shouldn't have to change/touch that much html/css...

![image](https://user-images.githubusercontent.com/1621749/34133154-0d127cd4-e408-11e7-8d35-56b69826e6d1.png)

**Comment by SeokbinKang** [comment]
<img width="1280" alt="before314_v2" src="https://user-images.githubusercontent.com/10859410/34133328-047d390a-e409-11e7-9b5e-3c7eea4aa984.png">

**Comment by SeokbinKang** [comment]
The vertical space between groups seems too much, or not?

<img width="599" alt="before314_v2" src="https://user-images.githubusercontent.com/10859410/34133346-19daa49a-e409-11e7-888e-d78c8e09dff6.png">

**Comment by jonfroehlich** [comment]
This is done via snippets. Eliminated use of headers, filtering, and groupby for now. Will have to add back later.
