### ISSUE TITLE
Project Gallery Filters Have To Be Hooked Up

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#315]
The project gallery filters have to be hooked up (see circled part below), which includes:

- Writing some backend code that associates primary keywords with each project
- Auto-filling the area and technology sidebar
- Hooking up the filter so that when selected, the list of projects is auto-filtered. We should use isotope for filtering imo: https://isotope.metafizzy.co/filtering.html

![image](https://user-images.githubusercontent.com/1621749/34090469-0fb22de6-e36c-11e7-8183-bede2b722171.png)

**Comment by higherdefender** [comment]
For this: 
- Writing some backend code that associates primary keywords with each project
can we pull something from the publications page? That seems to be working okay.

**Comment by higherdefender** [comment]
Also, I think we need to make it consistent with the publications page too. Why not just have this? The Area, Technology etc. can appear under "group by"

![image](https://user-images.githubusercontent.com/11636527/34125784-4bd18346-e3ec-11e7-8313-11c31702b19b.png)

**Comment by jonfroehlich** [comment]
For many reasons including that I like filtering more than the grouping and it's far more interactive--plus, I want to support hover filtering (e.g., it immediately shows you filter effect when you hover over the menu item).

**Comment by jonfroehlich** [comment]
In order for this to work, we actually need to update stuff in models.py, so removing this from Hackathon for now.

**Comment by ShivenBhatt** [comment]
This is fixed in #508.
