### ISSUE TITLE
Upload Files Using Link, or via Copy/Paste/Drag-and-Drop

### ISSUE THREAD

**Issue by lstearns86** [jonfroehlich/makeabilitylabwebsite#34]
These are minor convenience features that I think would be useful. Rather than requiring that admins download the file and then upload it from their file system, it may be simpler in some cases to enter a link or copy and paste or drag-and-drop. I'm not sure how Django's admin system will handle these cases, but I know there is HTML5/javascript support for it.

**Comment by jonfroehlich** [comment]
Probably not going to address this one (at least not for now).
