### ISSUE TITLE
Consider Adding Rich Text Editor Support to Certain TextFields

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#35]
For the news feed and other areas of the website, would be nice to have rich text editor support in the Django admin interface.

**Comment by jonfroehlich** [comment]
As @htadeusiak noted in https://github.com/jonfroehlich/makeabilitylabwebsite/issues/706, we also want to find a rich text editor for the new 'FAQ' page:

> Need to find a rich text editor plugin for Django. We are adding a FAQ page and want to add/edit content of this page via the Django admin interface.

@htadeusiak, do you think this is something within your skillset to start addressing? First step would be to do background research on options and propose one or two choices. Second step would be to play around with plugins and figure out which you like best. Third step would be integration.

**Comment by htadeusiak** [comment]
In addition to the two choices you recommend I'm going to look into 
3. https://djangopackages.org/packages/p/django-summernote/

I'm going to start playing around with these three.

**Comment by jonfroehlich** [comment]
Nice, summernote looks great (most recent release was 12/31/2018 as well). When evaluating these frameworks, we likely want to go with the most *popular* library that is also well supported. It would be frustrating and inefficient to spend time integrating a framework only for it to be dropped or unsupported.

**Comment by htadeusiak** [comment]
I tested Tinymce and CKEditor on my personal Django project. Out of the two I prefer CKEditor. It's fairly easy to implement and carries more features straight out the box such as a file/img uploader.

I have tried to implement this in my local branch but I keep getting an error when I run:
<code>$ python3 manage.py collectstatic </code>
This is one of the steps to implement CKEditor to the website. This line of code will copy static CKEditor required media resources into our directory.

Here is a screen shot of the error:
![screen shot 2019-01-25 at 6 00 52 pm](https://user-images.githubusercontent.com/33988444/51781269-3586fe00-20cb-11e9-9bc3-0d370f2961a8.png)

Do you have any ideas what it might be? If it's something not obvious don't waste your time on it, I'll keep trying different things.

**Comment by htadeusiak** [comment]
^^ I figured this out. I needed to install CKEditor package into the Docker environment and then run collectstatic in the Docker shell.

**Comment by htadeusiak** [comment]
I'm un-assigning myself after speaking with Jon. This issue should be solved after merging PR #773 

It will likely require consulting Jason to make sure it is properly installed on the test and production servers.

**Comment by jonfroehlich** [comment]
This is now on production and I've been using it to create News posts. Seems to work quite well. Yay! Thanks so much @htadeusiak!

We had this Issue open for 3+ years and now it's closed!!
