### ISSUE TITLE
Refactor code for Project/Person URL names

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#362]
Human-readable URLs for Projects and People are generated as columns in the SQL database. 

See: `models.py`
```
class Person(models.Model):
    url_name = models.CharField(max_length=50, blank=True, null=True)
...
class Project(models.Model):
    short_name = models.CharField(max_length=255)
...
class Project_umbrella(models.Model):
    short_name = models.CharField(max_length=255)
...
```
It would be nicer to make these functions, rather than database values.

**Comment by jonfroehlich** [comment]
In addition, I do not think this should be an editable field in the admin interface but rather auto-generated based on first+last name (if we switched this to a function, this would obviously be taken care of).

![image](https://user-images.githubusercontent.com/1621749/40751292-5fbb3682-641f-11e8-8e21-7fc3209c6f0b.png)
