### ISSUE TITLE
Bug in displaying future members under alumni

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#363]
Future members are marked as 'no longer active', which displays them in the alumni category on the website. We should maybe consider either:

1) not displaying future members until their start date
2) creating a separate category for future members

Currently, I think the only field we have to describe the status of members comes from the `is_active` function (in `models` > `Person`)

**Comment by jonfroehlich** [comment]
@aileenzeng, is this resolved? If so, you close this out?

**Comment by aileenzeng** [comment]
Yup - should be. Probably got fixed in #405
