### ISSUE TITLE
Django and Postgres aren't communicating properly

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#366]
Related issue: #361, #360 

On production, Django seems to think that the state of the database is different from what it actually is. This causes Postgres not to update its tables when `makemigrations` or `migrate` are run. The result of this is usually a ton of `Server Error: 500` on pages that involve tables that have been modified. This error happens locally (sometimes) too.

For now, it would probably be best to hold back from adding/removing fields in `models.py` since this is where changes to the database are made. If we do need to add/remove a field, we'll also need to update the schema (on UW servers) manually since Django isn't doing it automatically.

Since it looks like this might be a problem with Django, it might be worthwhile to try using a newer version, in case this bug has been addressed in a more recent update.

**Comment by jonfroehlich** [comment]
Hrmph. This is unfortunate. We likely need either a Django expert or a Docker expert (or both) to help us resolve this.

@aileenzeng, did you Google around at all for leads on this? Seems really weird tbh. We can, of course, try updating to a newer version of Django (locally first and then on makeabilitylab-test) to see if its fixed. I have a hunch, however, that it's not a Django problem (because creating new fields in models.py is a *basic* operation in Django--and any bug like this would have been super obvious and fixed immediately).

**Comment by aileenzeng** [comment]
@jonfroehlich I did Google around -- it seems like other people that had similar issues were able to fix it using `makemigrations` or `migrate` (bummer). Jason and I also tried to reset the migration history (hopefully forcing Django to recreate the database), but that didn't quite work either. It might be worth giving another shot.

I found this link that might be helpful: https://simpleisbetterthancomplex.com/tutorial/2016/07/26/how-to-reset-migrations.html

I'll take a look at how the `0001_initial.py` file (`website` > `migrations`) is getting updated, since I think this is the file that `makemigrations` is modifying.

**Comment by aileenzeng** [comment]
From @mechanicjay (07/16/18):
> From last weeks issues it seems that database migrations are still not
happening correctly when code is pushed to test and production sites.

> I think changing the approach here could be beneficial.

> It seems that there is a split among Django devs on how to handle
migrations when it comes to  dev/test/prod environments.   Some
recommend excluding the entire migrations directory from git (via
.gitignore) and letting Django do it's thing with the makemigrations and
migrate commands.  This is how we currently have things setup and its
apparent that this is NOT working.

> The other camp says to generate the migration files with makemigrations
on dev and version control them, then on production you only ever run
the migrate command. 

> This IN THEORY might work better for the multi-stage environment we're
in.  The only caveat is that the dev's need to careful of merge
conflicts and that they don't step on on the different migration
files.    I think it's worth and shot, and probably can't make things
worse....

**Comment by aileenzeng** [comment]
In #379, I added the `/website/migrations` folder to the `.dockerignore` file. I was thinking that if I didn't include the migrations folder that it would force Docker to do all the migrations again from scratch. (This seems to work fine locally for me -- I haven't ran into issues, but I'm not sure if this change could be causing issues on production)

**Comment by jonfroehlich** [comment]
According to @aileenzeng, this issue is still a problem. Whoever investigates this may want to setup their local dev environment to act exactly like the test/production servers (i.e., use PostgreSQL rather than sqlite) to debug, determine the problem, and then test a solution.

**Comment by jonfroehlich** [comment]
@johnsonkuang has been working on this and believes he may have a fix https://github.com/jonfroehlich/makeabilitylabwebsite/pull/807

**Comment by jonfroehlich** [comment]
Note: this is almost fully addressed. Need to push to production. Works on test.

**Comment by jonfroehlich** [comment]
This now appears to be fixed. Huge thanks to @johnsonkuang and to @mechanicjay and @aileenzeng. Yay!
