### ISSUE TITLE
Upload Images for People to UW Server

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#370]
Related issue: #344 

Some people are missing images for themselves. The x's in this table indicate that the image type  doesn't exist for this person yet. 

| Status  | Name | Regular | Star Wars |
| ------------- | ------------- | ------------- | ------------- | 
| Current  | Dhruv Jain (PhD) | x  | x  | 
| Current  | Simran Chawla  | x  | x | 
| Current  | Sarah Smolen  | x | x | 
| Current  | Johann Miller  | x | x | 
| Alumni  | Steven Bower | x | x | 
| Alumni | Aditya Dash  | x | x | 
| Alumni  | Chirag Shankar  | x | x | 
| Alumni  | Jason McPeak  |   | x |
| Alumni  | Andrew Matuza  | x |  | 
| Alumni  | Gideon Popkin  | x |  | 
| Alumni  | Andrew Lake | x |  | 
| Past Collaborators  | Cody Buntain  | x | x | 
| Past Collaborators  | Amy Green  | x | x |

**Comment by jonfroehlich** [comment]
Do the images exist on the server? We used to have images for Aditya, Jason, Gideon, etc. Can you check the media dir?

**Comment by aileenzeng** [comment]
@jonfroehlich I'm looking around in `/cse/web/research/makelab/www/person/`, which is where all the people images seem to be stored. I tried to find the images for maybe 5 people (matched up the path from the admin interface) and they didn't seem to be there

**Comment by jonfroehlich** [comment]
Weird. And now none of the people are showing up here: https://makeabilitylab.umiacs.umd.edu/people/. I'll need to ssh into the UMIACS servers and check out the media directory there...

**Comment by jonfroehlich** [comment]
Turns out that the fileserver on the UMIACS server needed to be rebooted. So, the media directory is back online. You can see all of the images of people here: https://makeabilitylab.umiacs.umd.edu/people/

**Comment by aileenzeng** [comment]
@jonfroehlich Ooh okay - this is great! I can probably take care of these upload issues then since I can access all the images from Chrome's Dev tools.

**Comment by aileenzeng** [comment]
Most of the regular images have been re-uploaded. I didn't find any face images for Andrew Matuza, Gideon, or Andrew Lake on the UMIACs site.

There currently isn't a way to choose an existing lego image for a user, so I decided not to upload any of those for now. I believe this was posted as an issue somewhere (but I can't seem to find it at the moment).

**Comment by jonfroehlich** [comment]
This is great. Thanks!

**Comment by aileenzeng** [comment]
Finished adding in Lego Pictures for everybody else - closing now!
