### ISSUE TITLE
Update video URL

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#371]
The video for _AtmoSPHERE: Representing Space And Movement Using Sand Traces_ doesn't exist anymore. Is there a different link for this video/could we reupload it onto YouTube to get a valid link?

**Comment by jonfroehlich** [comment]
Can you post the YouTube link here that it currently points to so I can investigate. Thanks!

**Comment by aileenzeng** [comment]
@jonfroehlich 
https://www.youtube.com/watch?v=W6fZNOhm72c

**Comment by jonfroehlich** [comment]
Can you switch it to this one: https://youtu.be/LZZAKrGy9eM?

**Comment by aileenzeng** [comment]
Sure thing! Closing this issue now.
