### ISSUE TITLE
Edited Publication PDF thumbnails aren't updating on production

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#372]
Related issue: #368 

Haven't tested it to see if this is true locally too. 

The PDF links work fine, and the small grey bar that should be the top of the thumbnail correctly links to the PDF. 
![image](https://user-images.githubusercontent.com/25534091/41179967-7b018a6e-6b21-11e8-9537-39f96808dc96.png)

I also SSH'd into the UW server and didn't see any new files in the `publications/images` folder.

**Comment by aileenzeng** [comment]
Manually updating the UW database works fine for now :)

**Comment by jonfroehlich** [comment]
@aileenzeng, I don't think this is a problem anymore... do you? Closing for now but we can reopen.
