### ISSUE TITLE
Server Error: 503 on Production Site

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#373]
I recently pushed a version of this repository  (`0.1.0`)  to https://makeabilitylab.cs.washington.edu and I'm getting a `Server Error 503`. When I visited the site earlier today, (~5 min. before pushing to production), I had gotten this error as well. In the past https://makeabilitylab.cs.washington.edu didn't give this error.

https://makeabilitylab-test.cs.washington.edu works fine.

Screenshot of the current page:
![image](https://user-images.githubusercontent.com/25534091/41184356-a1dff2b6-6b34-11e8-8050-dad711e7b7ef.png)

(Text: `Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.`)

I'm not sure if this could be related to the issue or not, but I inserted a couple thumbnail images directly into the CSE database.

@mechanicjay Any idea of what might be causing this?

**Comment by mechanicjay** [comment]
There were a couple of front-end proxy server directives that hadn't been migrated forward from test to prod.  That is now done and the site is looking much better now!

**Comment by aileenzeng** [comment]
Great, thank you so much! :)

@jonfroehlich Should we close this issue now?
