### ISSUE TITLE
Need to update news

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#374]
Now that we are starting to get somewhere in our transition from UMD to UW servers for the ML website, we need to update the news feed. I'd like to retrospectively add all major news items that have occurred since Oct 18, 2017 (including paper acceptances, awards, new lab members, new coverage, new funding, etc. etc.).

**Comment by johnsonkuang** [comment]
Comparison between center aligned buttons and left aligned

# centered
[![Image from Gyazo](https://i.gyazo.com/90ce94b2a687a2122462c8aaa64631b2.png)](https://gyazo.com/90ce94b2a687a2122462c8aaa64631b2)

# left aligned
[![Image from Gyazo](https://i.gyazo.com/c7834e088ac26c293e636e0e25a58a26.png)](https://gyazo.com/c7834e088ac26c293e636e0e25a58a26)

**Comment by jonfroehlich** [comment]
I like centered. :)
