### ISSUE TITLE
Update Readme.md with docker version

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#382]
@aileenzeng, can you update the readme.md to explicitly state which docker version we should use (enterprise or community edition). i was trying to mechanically test your documentation tonight and got stuck here. :)

![image](https://user-images.githubusercontent.com/1621749/41637364-5996b512-7408-11e8-9ab0-3fe13d9b29d7.png)

**Comment by aileenzeng** [comment]
@jonfroehlich Just added it! (I'm using the community edition)

**Comment by jonfroehlich** [comment]
So you just download the edition here? (I've done this twice before but it was a year ago so I can't remember...)

![image](https://user-images.githubusercontent.com/1621749/41637748-4f6f06dc-740a-11e8-9080-275c6022ddd2.png)

https://www.docker.com/community-edition#/download

Thanks for the fast response!

**Comment by jonfroehlich** [comment]
Ack, I've never seen a more confusing download experience. Now it takes me here after clicking download 'Docker CE for Windows'?

![image](https://user-images.githubusercontent.com/1621749/41637796-a083fb0e-740a-11e8-92f7-fa393d7eacfd.png)

**Comment by aileenzeng** [comment]
Yep! That's at least what I can remember from when I had downloaded it (I think the Get Docker button should do it)

**Comment by jonfroehlich** [comment]
OK, doing this now. Will report back tomorrow.
