### ISSUE TITLE
Update dev prereqs

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#383]
@aileenzeng, I added a new subsection to README.MD called "Dev Prereqs"--can you help me fill this out?

**Comment by aileenzeng** [comment]
Yup! I don't think we need to add anything else since everything else is installed in the Docker container. (Django is also included)

I threw in Git for good measure.

**Comment by jonfroehlich** [comment]
Great! Thanks.
