### ISSUE TITLE
Figure out a way to dev without having to rebuild/rerun the docker container

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#384]
When working on this website, we currently need to use `docker build` and `docker run` every time to reflect changes. This gets a little tedious to do.

There's probably some way that we can modify the `build` command so we don't have to keep rebuilding the container -- I'm guessing adding another volume mount should do it.

**Comment by jonfroehlich** [comment]
Yes, I briefly mentioned this to Elliot about one of the (rather serious) pains I discovered when dev'ing with Docker. Would be good to come up with a solution.

**Comment by aileenzeng** [comment]
@jonfroehlich Good news! I just tested an idea that I had - it seems to fix this problem. Updating the README now.

**Comment by jonfroehlich** [comment]
Amazing. You rock.

**Comment by jonfroehlich** [comment]
@aileenzeng, did you accidentally link to the wrong commit above?

**Comment by aileenzeng** [comment]
@jonfroehlich Oops - I did! Just updated my comment to include to the correct one.
