### ISSUE TITLE
Write 'process for contributing code' section on readme.md

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#385]
Can be based on this: https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Process-for-contributing-new-code but does not need to be as sophisticated (because this is just a research group website); however, I do like creating ~one branch per issue, and doing code review on PRs, etc.

**Comment by aileenzeng** [comment]
It seems like Github's standard is to add a `CONTRIBUTING.md` file. It might be nice to have a separate file since the README is getting pretty long? Just a thought.

**Comment by jonfroehlich** [comment]
Can you auto-generate table of contents using markdown?

**Comment by aileenzeng** [comment]
I don't know about auto-generating table of contents, but it looks like markdown does have support for manually generated table of contents. 

Example: https://gist.github.com/jonschlinkert/ac5d8122bfaaa394f896#heading

**Comment by aileenzeng** [comment]
Update: I have a branch open for this (`contributing-guide`), but I'm not sure it's specific enough?
