### ISSUE TITLE
Make Talks left-align consistently

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#386]
Talks sometimes don't left-align properly (see below):
![image](https://user-images.githubusercontent.com/25534091/41743714-7ea7a7d6-7556-11e8-91c9-cfe845a938c6.png)

**Comment by jonfroehlich** [comment]
This is fixed on the landing page. See:

![image](https://user-images.githubusercontent.com/1621749/41747406-c094ca64-7562-11e8-9a52-200fb506fa50.png)

**Comment by ShivenBhatt** [comment]
We have a new ticket for this here: #530. I'm closing this issue.
