### ISSUE TITLE
Fix news overlap on banner

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#388]
The banner on the front page looks like this:

On mobile, I think it might be cleaner to make news its own section on the landing page. (This is what was done for the UMIACS site). I'd love to hear more thoughts on this.

|Current | UMIACS |
| ------- | --------- |
| ![image](https://user-images.githubusercontent.com/25534091/41744132-a85501d6-7557-11e8-92ae-26ccdb980341.png) | ![image](https://user-images.githubusercontent.com/25534091/41744295-3d3644d6-7558-11e8-961b-6c8cfdb152a5.png) |

**Comment by jonfroehlich** [comment]
Thanks @aileenzeng. Based on a vote from Makeability Lab members, a strong majority were in favor of moving from a two-column landing page to a one-column landing page. Hence the change from the UMIACS site (the screenshot on the right).

Note, however, that this overlay news thing was highly experimental and is still in draft form. In parallel, we were developing a landing page news module (see Mockup1 and Mockup2) here (https://github.com/jonfroehlich/makeabilitylabwebsite/issues/289). I thought @EdigaHe was working on this--not sure what the current state is. Perhaps @johnsonkuang can take it over when he starts working on others News-related Issues.

**Comment by jonfroehlich** [comment]
I think we can just hide the news overlay on mobile. @johnsonkuang, can you do this?

**Comment by johnsonkuang** [comment]
This issue has already been addressed, #408 addresses the needed changes. So I think we can close this issue. The restriction placed on the screen width is 600 px, anything wider than that will display the overlay banner, narrower and it will set display to none.
[![Image from Gyazo](https://i.gyazo.com/2d1a58d6890de0fde19da80af79e62a2.png)](https://gyazo.com/2d1a58d6890de0fde19da80af79e62a2)
