### ISSUE TITLE
Filter sidebar gets hidden behind footer

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#412]
This happens on projects/publications/talks.

Example:
![image](https://user-images.githubusercontent.com/25534091/42465158-011d164e-8360-11e8-8f8c-f42268711a5f.png)

**Comment by alexjk38** [comment]
Short video clip after change: https://cl.ly/3n443B3V2Y3x
After screenshot:
<img width="1440" alt="screen shot 2018-07-21 at 1 56 34 am" src="https://user-images.githubusercontent.com/32470028/43034037-55681898-8c89-11e8-8684-704d0af88746.png">

**Comment by jonfroehlich** [comment]
Can you add a brief before video clip too so we can see difference? Nice job

**Comment by alexjk38** [comment]
Should be included now

**Comment by johnsonkuang** [comment]
PR Merged, closing issue
