### ISSUE TITLE
Navbar scalability

### ISSUE THREAD

**Issue by johnsonkuang** [jonfroehlich/makeabilitylabwebsite#418]
While preparing the website to be ready for production, I've encountered a scalability problem in the navbar. When the screen is wider than a set number of pixels, the navbar will stop expanding, as such, it will cease to scale with the screen-width. When checking the CSS responsible, I've found that the code responsible are the media queries set in `grid.less`. 
[![Image from Gyazo](https://i.gyazo.com/ace1a4c3a34c3085839a1b295139c871.png)](https://gyazo.com/ace1a4c3a34c3085839a1b295139c871)

This causes problems when accessing the site from a device with a screen wider than that of a Mac due to the fixed maximum that the screen will scale to, leading to a visual inconvenience where the navbar stops expanding: 

This is a screenshot taken from my computer, note that the logo and the right most link is significantly farther from the edge of the screen.
[![Image from Gyazo](https://i.gyazo.com/d9f9c32102c957f74015c7630426031f.jpg)](https://gyazo.com/d9f9c32102c957f74015c7630426031f)

Thoughts on whether we should adjust this?

**Comment by jonfroehlich** [comment]
If I recall, I believe we decided that all content should remain within that 750px width container; however, some newer code that I wrote deviates from this because this decision came afterwards...

**Comment by jonfroehlich** [comment]
We can talk more about this tomorrow. I hope to be on campus...
