### ISSUE TITLE
Mouseover on links in citation pop-up shows wrong cursor

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#421]
When mousing over Citation or Bibtex in this Citation pop-up for publications, the mouse cursor should change to a pointer finger (currently changes to a flashing edit cursor)

![image](https://user-images.githubusercontent.com/1621749/42544138-6ef86308-8464-11e8-95ea-c87e4f0d4fcc.png)

This happens at least on the landing page (haven't tested it on the pubs page)

**Comment by johnsonkuang** [comment]
@jonfroehlich 
[![Image from Gyazo](https://i.gyazo.com/61f6d7ff29b4bff5dbf54deaede400e0.gif)](https://gyazo.com/61f6d7ff29b4bff5dbf54deaede400e0)
is this what you envision?

**Comment by jonfroehlich** [comment]
Yes. Thank you. And awesome post with an animated gif and everything. Please keep up this high quality work!! 👍🏽

**Comment by johnsonkuang** [comment]
Pull request submitted and merged, closing issue
