### ISSUE TITLE
Citation popover is cut off (mobile)

### ISSUE THREAD

**Issue by johnsonkuang** [jonfroehlich/makeabilitylabwebsite#423]
While PR #422 fixes the cut off problem on a computer, the mobile version still has issues. 
[![Image from Gyazo](https://i.gyazo.com/0575f070e075d19995e2878b88c5de41.png)](https://gyazo.com/0575f070e075d19995e2878b88c5de41)

**Comment by jonfroehlich** [comment]
One solution may be to simply hide this link on mobile screens since I doubt people on mobile would need that functionality...

**Comment by johnsonkuang** [comment]
I could simply set up a media query to hide it after a certain max screen-width

**Comment by johnsonkuang** [comment]
I'll add that to PR #422

**Comment by jonfroehlich** [comment]
Let’s try it.

**Comment by johnsonkuang** [comment]
Pull request merged #422
