### ISSUE TITLE
Shouldn't the media folder be in .gitignore?

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#426]
I just setup my dev environment using @aileenzeng's awesome docker instructions. I also bootstrapped some pub content using importpubs; however, in doing so, I now have 833 changes to be committed--all because my media/* folder has content (see screenshot). So, shouldn't we have media/ added to gitignore?

![image](https://user-images.githubusercontent.com/1621749/42606099-6301416a-8530-11e8-992e-4b81a7ee865b.png)

I think @johnsonkuang was also experiencing some issues with this because he said that the `debug.log` kept getting added to his commits.

**Comment by aileenzeng** [comment]
Definitely agree — I think they had been removed sometime earlier on by mistake when I had been doing the docker stuff way earlier on during the summer (oops!).
