### ISSUE TITLE
Docker install for Windows failed

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#429]
After running `docker build . -t makelab_image` for the first time, I received this error:

> Err http://security.debian.org/ jessie/updates/main imagemagick-6.q16 amd64 8:6.8.9.9-5+deb8u11
>   404  Not Found [IP: 128.31.0.63 80]
> E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/imagemagick-6.q16_6.8.9.9-5+deb8u11_amd64.
> deb  404  Not Found [IP: 128.31.0.63 80]
> 
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> Fetched 14.1 MB in 4s (3529 kB/s)
> The command '/bin/sh -c apt-get --assume-yes install imagemagick ghostscript sqlite3' returned a non-zero code: 100

**Comment by jonfroehlich** [comment]
I just tried this on a second Windows machine and ran into the same issue:

```
Get:21 http://security.debian.org/ jessie/updates/main libgs9 amd64 9.06~dfsg-2+deb8u6 [1916 kB]
Err http://security.debian.org/ jessie/updates/main imagemagick-6.q16 amd64 8:6.8.9.9-5+deb8u11
  404  Not Found [IP: 128.31.0.63 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/imagemagick-6.q16_6.8.9.9-5+deb8u11_amd64.
deb  404  Not Found [IP: 128.31.0.63 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by jonfroehlich** [comment]
Fixed it. Lots of people talking about this problem on the web. The fix was to change the apt-get stuff to a single line in the Dockerfile:

```
# Setup some other prereqs needed:
RUN apt-get update
RUN apt-get --assume-yes install imagemagick ghostscript sqlite3 

```
to:
```
# Setup some other prereqs needed:
RUN apt-get update && apt-get --assume-yes install imagemagick ghostscript sqlite3 
```

**Comment by jonfroehlich** [comment]
Argh, almost there. I got through every step except for now I'm stuck on Step 13 of the readme.md instructions:

> Run the local server using Docker. Use `docker run -p 8000:8000 -ti -v ${pwd}/db:/code/db -v ${pwd}/media:/code/media -v ${pwd}/website:/code/website [tag]`

I tried doing that but received an error:
```
PS D:\Git\makeabilitylabwebsite> docker run -p 8000:8000 -ti -v ${pwd}/db:/code/db -v ${pwd}/media:/code/media -v ${pwd}/website:/code/website makelab_image
standard_init_linux.go:190: exec user process caused "no such file or directory"
```

**Comment by jonfroehlich** [comment]
Hmm, from my reading, this may be related to LF vs. CRLF line endings on Linux vs. Windows. I don't think I did Step 6 from the instructions, which state:

> Before you clone the repository, run this command `git config --global core.autocrlf false` in the directory you will be cloning the repository to. Windows crlf is unrecognized in Linux, thus we must set this auto-conversion as false to prevent look-up errors.

I'm gonna try again but do this and report back. Since I use the github desktop tool, not sure how to do this exactly...

**Comment by jonfroehlich** [comment]
Aha, so following Step 6 fixed it. Yay!

**Comment by ShivenBhatt** [comment]
Thanks @jonfroehlich!
