### ISSUE TITLE
Talk Admin: Auto Generate Short_Title (i.e., Displayed Talk Title)

### ISSUE THREAD

**Issue by mattm401** [jonfroehlich/makeabilitylabwebsite#44]
Implement auto generation of Short Title: use a character count that cuts off at closest word under maximum and then has ellipses at end to indicate the cutoff. Also, set a good maximum as current 100 char limit was set somewhat arbitrarily.

**Comment by jonfroehlich** [comment]
We now handle all of this on frontend, which is the right approach imo. Closing.
