### ISSUE TITLE
Something wonky with displaying talks when on small'ish size browser window

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#441]
If you resize your browser window (see screenshot), the talks on the landing page are not displayed correctly. The title suddenly spans the entire row. Instead, the desired behavior here is just to still see multiple talks per column. In the screenshot, for example, it should be 2 talks per column.

![image](https://user-images.githubusercontent.com/1621749/42712159-605a4680-869f-11e8-91d6-b4c3395469b2.png)

Here's another example. The title and text (etc) should fall within the horizontal extents of the image above it. 

![image](https://user-images.githubusercontent.com/1621749/42830430-420f84d4-89a0-11e8-8196-11320f246793.png)

**Comment by ShivenBhatt** [comment]
This was fixed when we merged #460. The fix is already on the website. We should close this issue.

**Comment by ShivenBhatt** [comment]
This was fixed when we merged #460. The fix is already on the website. I'm closing this issue.
