### ISSUE TITLE
Some member pages not loading on test

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#444]
Some member pages are returning a Server 500 Error (for varying reasons).

| Person | ID | Page | Fixed |
| ------- | -- | ---- | ------ |
| Jon Froehlich | | https://makeabilitylab-test.cs.washington.edu/member/jonfroehlich/ | |
| Dhruv Jain | | https://makeabilitylab-test.cs.washington.edu/member/dhruvjain/ | |
| Henri ter Hofte | 364 | https://makeabilitylab-test.cs.washington.edu/member/henriterhofte/ | x |
| Kasper L. Jensen | 365 | https://makeabilitylab-test.cs.washington.edu/member/kasperjensen/ | x |
| Peterri Nurmi | 366 | https://makeabilitylab-test.cs.washington.edu/member/petterinurmi | x |
| James Landay | 314 | https://makeabilitylab-test.cs.washington.edu/member/jameslanday/ | x |
| T. Scott Saponas | 408 | | x |

I don’t think it’s an issue of his url name not being generated correctly (the link to his page is correct when I hover over it + I would have expected a Server 500 Error on the entire People page). I think this has something to do with one component that displays on his page that isn’t loading correctly. I’ll look into the debug log more tonight to see if I can get anything more specific.

**Comment by jonfroehlich** [comment]
This is another space in the name problem like Victor De Souza. This time it’s Henri Ter Hofte. We just need to manually update that name in admin so that url_name is recalculated with Aileen’s replace white space fix.
