### ISSUE TITLE
Project layout breaks on landing page on page resize

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#448]
Correct:
![image](https://user-images.githubusercontent.com/1621749/42768438-5ab22f90-88d4-11e8-830d-3aa72874be34.png)

Then as I shrink window, thumbnails collide and overlap:
![image](https://user-images.githubusercontent.com/1621749/42768470-6ca751bc-88d4-11e8-8f28-54a3cefd3d25.png)

Note that the Recent Videos part of the webpage seems to do what we want, so possibly adopt that approach?

**Comment by ShivenBhatt** [comment]
This was resolved when we merged #460. Fix is already on the website:
![image](https://user-images.githubusercontent.com/21998904/43473288-9564c2b6-94a4-11e8-8ba2-8627efe98ae7.png)
We should close this issue.

**Comment by ShivenBhatt** [comment]
This was resolved when we merged #460. Fix is already on the website:
![image](https://user-images.githubusercontent.com/21998904/43473288-9564c2b6-94a4-11e8-8ba2-8627efe98ae7.png)
I'm closing this issue.

**Comment by jonfroehlich** [comment]
I actually have a comment about this and it’s behavior. So can we reopen? Otherwise, I guess I can open a new ticket.

**Comment by ShivenBhatt** [comment]
reopening issue.

**Comment by jonfroehlich** [comment]
I don't like how the items resize (and the black shadows/outlines that then exist). Why does that happen now? Why can't things just resize like on the [people page](https://makeabilitylab-test.cs.washington.edu/people/) and the [talks page](https://makeabilitylab-test.cs.washington.edu/talks/). Note how here the size of the thumbnails stays the same. Why the difference?

**Comment by ShivenBhatt** [comment]
I initially did it because when the landing page had other issues you asked me to copy the video behavior for talks and projects, since that worked. The video behavior at the time included black backgrounds and scaling, so I copied that behavior.

This shouldn't be too difficult to implement. I'll get back with the fix soon.

**Comment by jonfroehlich** [comment]
I think the current behavior for the videos is fine but not for other subsections. Thanks.
