### ISSUE TITLE
Star Wars Image upload not working on Django 2.0

### ISSUE THREAD

**Issue by johnsonkuang** [jonfroehlich/makeabilitylabwebsite#452]
The easter egg code that randomly selects an easter egg image for each person saved has broken in Django 2.0 due to a suspicious file operation conducted when the code looks in the imports directory for a random image. As such, I believe we have to move the images to the media directory; however, there we encounter another problem related to attempting to navigate to the correct directory. As two copies of files exist (in docker and locally), the method of retreiving a random image would need to be revised, either by:
1. copying the images into the media directory in the docker container
2. adjusting the local path to return the absolute path of the image stored locally

**Comment by jonfroehlich** [comment]
Can you update this Issue with more details. Please include the current path where the SW figures are being stored, the exact error that you are receiving (with links to online discussions about it, if possible), your exact proposed path change.

**Comment by johnsonkuang** [comment]
I don’t have a screen cap of the exact error I’m receiving, however the original path was to navigate to the base directory and then append ‘/import/images/StarWarsFiguresFullSquare/Rebels/’ to it. I would suggest a similar approach; however, we cannot navigate to the base directory in the same way because the code is running from docker and the images are stored locally.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by johnsonkuang** [comment]
could we somehow keep the images online and then random select from there?

**Comment by jonfroehlich** [comment]
The solution is to just have them in the media dir imo, as we discussed.
