### ISSUE TITLE
"To appear" is showing up for every pub

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#456]
"To appear" is showing up for every pub. It should only show up for those pubs that have a publication date ahead of the current date.

![image](https://user-images.githubusercontent.com/1621749/42911623-a815f960-8aa0-11e8-9a9b-6725f76e375f.png)

**Comment by jonfroehlich** [comment]
I tried fixing this briefly but couldn't figure it out. See branch https://github.com/jonfroehlich/makeabilitylabwebsite/tree/fix-to-appear-bug-on-pubs. Note that if we isotopify this page, then we'll no longer rely on the javascript version to show/hide fields anyway...

**Comment by jonfroehlich** [comment]
@johnsonkuang can you take a look at this one?

**Comment by johnsonkuang** [comment]
PR Merged, closing issue
