### ISSUE TITLE
Fix alignment of h4 subheaders on people page

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#463]
The h4 subheaders are not properly left aligned with the h1s and content:

![image](https://user-images.githubusercontent.com/1621749/42961115-a3a84ad4-8b42-11e8-9b7e-f51f0eed9adf.png)

@ShivenBhatt, perhaps you can fix this when you isoptopify this page.

**Comment by ShivenBhatt** [comment]
This is resolved in #472

**Comment by ShivenBhatt** [comment]
This was resolved when we merged #470. Fix is already on the website:
![image](https://user-images.githubusercontent.com/21998904/43473100-0bd260d0-94a4-11e8-809b-a7edfeb6227a.png)

**Comment by jonfroehlich** [comment]
Thanks. Closing.
