### ISSUE TITLE
News Page Issues

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#467]
We just pulled @johnsonkuang's news-listing stuff to master but there are a few problems.

![image](https://user-images.githubusercontent.com/1621749/43002022-2f2daf88-8bdc-11e8-9192-d6e7d496b183.png)

- [x] The thumbnail showing on the news-listing should be the actual image used in the news item. If and only if no image was supplied should the thumbnail default to the "news icon" image. Currently, all thumbnails are the "news icon" image (see screenshot above)
- [x]  The news text is being rendered as plaintext but should be rendered as html (see screenshot above)
- [x] We still need to decide if the blurb should be limited by characters or by line length (i.e., line clamping)

**Comment by johnsonkuang** [comment]
first two problems have been resolved

I'm interested in how line clamping would work and would be willing to experiment with it for the time being.

**Comment by johnsonkuang** [comment]
PR merged, closing issue
