### ISSUE TITLE
Remove strange dependency so website will work with empty database

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#468]
@johnsonkuang made some sort of change in the Django 2.0 upgrades that breaks hosting the website from a fresh build (with no data). This should not happen and needs to be fixed.

@johnsonkuang, can you fill in the particulars of the problem below and then prepare a fix. We (@johnsonkuang, me, and @ShivenBhatt) discussed this yesterday.

**Comment by johnsonkuang** [comment]
Pull request submitted and merged, closing issue.
