### ISSUE TITLE
Background missing on overlay (mobile)

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#489]
![7f928be8-412d-4315-8a8a-c2d896e58ba8](https://user-images.githubusercontent.com/25534091/43268600-e708d506-90a5-11e8-80a6-6ba1d71553f1.png)

This seemed to be working yesterday afternoon — must have been broken in a recent PR.

**Comment by jonfroehlich** [comment]
Good catch. May have broken in Shiven’s menu bar PR

**Comment by ShivenBhatt** [comment]
This was fixed by #491. Closing this issue now.
