### ISSUE TITLE
Bug in isotope filtering on people page

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#496]
If you click on a filter and then click somewhere else, the filter is not reset.

![makeabilitylabfilterbarbroken](https://user-images.githubusercontent.com/1621749/43284495-d540dce4-90d0-11e8-8113-ad651ab2d4c5.gif)

**Comment by ShivenBhatt** [comment]
Just to be clear, do we want the filter bolding to stay after an 'away' click like this?
https://www.youtube.com/watch?v=wqneDskqoDA&feature=youtu.be
Or do we want the filter to revert to 'All'?

**Comment by jonfroehlich** [comment]
We want the filter bolding (and the filter) to stay active unless the user clicks on a different filter

**Comment by jonfroehlich** [comment]
Also, I see that in your video, you moved All to the beginning of list. I think it's fine to have at the end of the list. So, please don't change that order.

**Comment by ShivenBhatt** [comment]
ok
