### ISSUE TITLE
Publication listing broken in Firefox

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#501]
Firefox does not show all of the publications loaded in the database. It has a NaN category on left sidebar with 33 entries:

![image](https://user-images.githubusercontent.com/1621749/43293845-23615f64-90f1-11e8-966e-775a01bfeaa9.png)

In addition, when you click on the sidebar, you receive
`TypeError: clickedElement is undefined[Learn More] publications:6099:1 `

**Comment by johnsonkuang** [comment]
Pull Request #515 addresses this issue, closing issue
