### ISSUE TITLE
Responsiveness of Recent Projects and Recent Talks Broken

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#522]
Ideally, when you shrink down the webpage, the "Recent Projects" and "Recent Talks" content would not show a massive gap as the columns go from four to three. Instead, I would hope for much more fluid scaling (like the thumbnails shrink or the margins between thumbnails shrink or something)--much more like Recent Papers.

See: https://media.giphy.com/media/1ykCOH5Ak30uPvbhFF/giphy.gif

@ShivenBhatt, thoughts on how to do this? Do we go back to the previous fix you had for this? I didn't like that because of all of the black shadows...

**Comment by ShivenBhatt** [comment]
I could remove the black shadows, then we would just have a resizing thumbnail. In that case, the alignment problems with "see all" would also be fixed.

**Comment by jonfroehlich** [comment]
Great idea. Let’s try it!
