### ISSUE TITLE
Oops, why aren't eight projects showing on landing page

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#524]
![image](https://user-images.githubusercontent.com/1621749/43613809-c4f2a3d2-9665-11e8-81a0-476ab6472412.png)

My guess is this is related to a fix by @alexjk38. He didn't realize that we prefilter the list of projects to eight using Django's template language but his code checks for "empty projects" and doesn't display those and so we never actually get to eight on the landing page.

**Comment by jonfroehlich** [comment]
Yep.

**Comment by jonfroehlich** [comment]
@alexjk38 did you fix this? Can you give us an update?

**Comment by alexjk38** [comment]
@jonfroehlich This is finished. I believe that johnson was set to review the pull request, just waiting for authorization
