### ISSUE TITLE
Just uploaded a talk but get 403 Forbidden when trying to download it

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#527]
I just uploaded a talk on makeability-test and while it shows up on the landing page, when I click on it, I get a 403 Forbidden page. Interestingly, I've uploaded and tested publications and those work fine... but just not the talks. I wonder why...

![image](https://user-images.githubusercontent.com/1621749/43614473-7656ef0a-9668-11e8-8205-1a612fe70d75.png)

![image](https://user-images.githubusercontent.com/1621749/43614434-4bd68dee-9668-11e8-8357-e0388a8b6b98.png)

**Comment by aileenzeng** [comment]
@mechanicjay Do you think you could take a look at this issue when you have time? (I didn't see anything in the `debug.log` that looked relevant)

**Comment by jonfroehlich** [comment]
@aileenzeng, can you try clicking on a talk pdf and then verify that the talk pdfs are actually on the server?

**Comment by jonfroehlich** [comment]
OK, in a meeting with @mechanicjay, he said that something is wrong on his end--some files (talks and pubs) are not getting the right permissions...

**Comment by jonfroehlich** [comment]
@mechanicjay fixed the problem by changing the permissions manually but has a theory about what we need to change in our docker file to ensure this doesn't happen in future.

**Comment by aileenzeng** [comment]
@jonfroehlich Looks like everything is on the server. (Files that we can't open have their owner as `nfsnobody`).
