### ISSUE TITLE
Talks page has weird gaps in rows sometimes

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#530]
![image](https://user-images.githubusercontent.com/1621749/43615127-12343836-966b-11e8-828f-9d7b4aff6844.png)

We need to update the talk rendering anyway to use a snippet (based on landing page) and to isotopify the page... Can take care of this when we do that...

**Comment by ShivenBhatt** [comment]
That's weird, #399 should have fixed this. When I look at talks.css on the master, the change is there, but it's not there on the website.  The issue should be fixed if we can find a way to get the changes made in #399 onto the website.

**Comment by jonfroehlich** [comment]
Also exists on project pages. For example, on the BodyVis project page:

https://makeabilitylab-test.cs.washington.edu/project/BodyVis/

Ultimately, we need to fix this by using snippets because there is an incredible amount of copy/pasted code currently for all sorts of things (e.g., talk rendering code exists on landing page, talks page, project page, and an individual person's page). This should just be one snippet that we call.

**Comment by jonfroehlich** [comment]
@johnsonkuang, can you investigate this please?

**Comment by johnsonkuang** [comment]
Alignment is correct on the talks page:
[![Image from Gyazo](https://i.gyazo.com/5dfb9ef0fa60c8c4c82d57a1ff3b4fd9.png)](https://gyazo.com/5dfb9ef0fa60c8c4c82d57a1ff3b4fd9)
