### ISSUE TITLE
Makeability Lab API needs to support people, news, videos, and projects

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#554]
The Makeability Lab API needs to support people, news, videos, and projects. We should also add support to import that information to enable better testing in the dev environment.

**Comment by johnsonkuang** [comment]
The original issue only contained references to bootstrapping talks and pubs, but this can be added as well.

**Comment by johnsonkuang** [comment]
PR merged closing issue
