### ISSUE TITLE
Videos Page: When viewing by 'Project', the videos with no Project have no header

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#568]
The talks that have no associated project are positioned first on the page. Instead, I would give them the 'Other' Category and put them at the bottom. Also, these talks currently have no header--we should put the header as 'Other'

![image](https://user-images.githubusercontent.com/1621749/44285512-893b1480-a21a-11e8-922a-ce4babd89078.png)

**Comment by ShivenBhatt** [comment]
Misname of title. fixed. :)

**Comment by jonfroehlich** [comment]
Tested on makeabilitylab-test.... looks good.
