### ISSUE TITLE
Responsive footer on mobile looks like crap :)

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#571]
![image](https://user-images.githubusercontent.com/1621749/44290135-26527900-a22c-11e8-8c0b-79b28aeb970d.png)

Both the blue part and the black part.

**Comment by jonfroehlich** [comment]
We should study how other pages do mobile footers, sketch out some of our own ideas, and then prototype!

**Comment by jonfroehlich** [comment]
This is what we were talking about in today's ML meeting @higherdefender.

**Comment by jonfroehlich** [comment]
Thanks for doing this. I certainly did not intend for us to only look at academic websites to inform our designs--indeed, I think it's best to look outwards at professionally designed sites for guidance. I do want a footer.

Can you find ~10 more examples from professional sites. Maybe try etsy.com, dribbble.com, and other design'y sites.

**Comment by higherdefender** [comment]
On it.

**Comment by jonfroehlich** [comment]
I explored this a bit today. Of the sites I visited, I like the UW CSE footer the best. I'll try to design a mockup soon.

![img_8690](https://user-images.githubusercontent.com/1621749/47356551-56027f00-d6bc-11e8-97a5-99c9ff8518da.PNG)
![img_8691](https://user-images.githubusercontent.com/1621749/47356552-56027f00-d6bc-11e8-89d8-1b2e19286916.PNG)
![img_8689](https://user-images.githubusercontent.com/1621749/47356555-56027f00-d6bc-11e8-867a-1c9f7029f956.PNG)
![img_8688](https://user-images.githubusercontent.com/1621749/47356556-569b1580-d6bc-11e8-8000-b2882a89bf49.PNG)
![img_8680](https://user-images.githubusercontent.com/1621749/47356557-569b1580-d6bc-11e8-9519-3cc86e0a2008.PNG)

**Comment by jonfroehlich** [comment]
Here are two mocks. Any opinions? I cut the Recent News part (available on full screen views) as I think it unnecessary for smartphone footer. @EdigaHe, any thoughts? @higherdefender, can you implement this? I like the one on the left best.

![image](https://user-images.githubusercontent.com/1621749/47357021-8ac30600-d6bd-11e8-9b2f-150ebab840c2.png)

**Comment by jonfroehlich** [comment]
Oops, accidentally closed.

**Comment by jonfroehlich** [comment]
@higherdefender has been working on this.

**Comment by jonfroehlich** [comment]
@higherdefender did a nice job on this in https://github.com/jonfroehlich/makeabilitylabwebsite/pull/690. Here's the animated gif of the final solution. Note that the affiliation bar on the bottom (black banner) still needs to be fixed.

![dhruvsmobilefooter](https://user-images.githubusercontent.com/1621749/48381748-575b1200-e692-11e8-8491-ac19885b8163.gif)
