### ISSUE TITLE
Default sort for videos on video page should be by date

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#572]
Not sure how they are sorted now but it's certainly not by date as it should be (reverse chronological so newest videos are first):

![image](https://user-images.githubusercontent.com/1621749/44290853-931b4280-a22f-11e8-8a5d-170c12d598fc.png)

**Comment by ShivenBhatt** [comment]
Easy way to fix. In the 'Date' class in the isotope grid, replace this:
```{{video.date.year}}{{video.date.month}}{{video.date.day}}```
with this:
```{{ video.date|date:"U" }}```

**Comment by jonfroehlich** [comment]
This doesn't work perfectly because the videos still come in unsorted and then you get this disorienting isotope re-ordering visualization to sort them by date... they should be defaulted to being sorted reverse chronologically.

**Comment by jonfroehlich** [comment]
OK, fixed this in https://github.com/jonfroehlich/makeabilitylabwebsite/commit/d348d6f12609eba428811ad9ee736730b6c8079a by adding order_by to the query `Video.objects.filter(date__range=["2012-01-01", date.today()]).order_by('-date'),`

**Comment by jonfroehlich** [comment]
Still has a weird disorienting layout animation on load, however.
