### ISSUE TITLE
Default sorting for projects should be by most recently published paper

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#573]
The default sorting for projects should be by most recently published paper (projects with more recently published papers should show first and then sort order is in reverse chronological)

![image](https://user-images.githubusercontent.com/1621749/44290895-ccec4900-a22f-11e8-8aae-b28269677bfd.png)

**Comment by ShivenBhatt** [comment]
Easy way to fix. In the 'Date' class in the isotope grid, replace this:
```{{video.date.year}}{{video.date.month}}{{video.date.day}}```
with this:
```{{ video.date|date:"U" }}```

**Comment by jonfroehlich** [comment]
But what is project.date?

**Comment by ShivenBhatt** [comment]
sorry, should be ```{{ project.get_most_recent_publication|date:"U" }}``` not ```{{ project.date|date:"U" }}```. In any case, this is fixed in #579. #572 and #568 are fixed in #579 as well.

**Comment by jonfroehlich** [comment]
Needs to be tested on makeability-test

**Comment by jonfroehlich** [comment]
I completely redid the projects.html page and they are now sorted by the function `sort_projects_by_most_recent_artifact`
