### ISSUE TITLE
Talk authors on landing page should link to member name

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#580]
Currently links to Member ID -- should be linking to member names instead (this should link to https://makeabilitylab.cs.washington.edu/member/leestearns/)
![image](https://user-images.githubusercontent.com/25534091/44439080-03e79500-a577-11e8-8239-f0670a077423.png)

**Comment by jonfroehlich** [comment]
this is fixed!

![image](https://user-images.githubusercontent.com/1621749/46383347-c6415600-c664-11e8-968c-a4c3132cdff6.png)
