### ISSUE TITLE
Cleanup duplicate people

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#582]
There are lots of duplicate people/authors. Each duplicate should be consolidated/merged into a single person.

**Comment by htadeusiak** [comment]
I went through and deleted all of the obvious duplicated members. There are some members with a lot of empty spaces as shown in the picture below. Should I leave these members or take them out?
<img width="1207" alt="screen shot 2019-03-01 at 9 48 05 pm" src="https://user-images.githubusercontent.com/33988444/53677861-c96c5c80-3c6b-11e9-8b8b-947f3bc5f21e.png">

**Comment by jonfroehlich** [comment]
Can't answer your question because I'm not sure who these people are in the rows. :)

In terms of duplicates, one concern I have with this is that deleting the person may affect the artifacts that they may be attached to: like paper associations, talk associations, etc.

Instead of deleting duplicates, I was thinking we may want to merge.

**Comment by htadeusiak** [comment]
When I went through the first time I made sure the duplicates I deleted were not associated with any other objects. There is a feature on the admin page when you go to delete someone is shows the other objects they are asserted with:
![screen shot 2019-03-02 at 3 22 46 pm](https://user-images.githubusercontent.com/33988444/53688858-58768480-3cff-11e9-8631-cbcb7a4d96a1.png)

**Comment by htadeusiak** [comment]
So as long as a person is not asserted with any other objects (such as news articles and publications) can I go ahead and remove them?

**Comment by jonfroehlich** [comment]
Right, as long asa person is not associated within object, we can remove them.

**Comment by htadeusiak** [comment]
Are 'Ji Hyuk Bae' and 'Sean Bae' the same person. He has a high school profile and undergrad profile, should I combine them?

**Comment by jonfroehlich** [comment]
Different person! They are brothers! :)

And Ji worked with us both when he was in high school and as a ugrad just like Anthony Li.

**Comment by htadeusiak** [comment]
This should be cleared up. All duplicates were removed along with any person object with out being asserted with another object such as a publication or news article.
