### ISSUE TITLE
Upload Ondule publication

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#600]
Paper: Designing 3D-Printed Deformation Behaviors Using Spring-Based Structures: An Initial Investigation.

Accidentally deleted this publication (sorry!) when trying to close out #578 and received a Server 500 Error when I tried to re-upload.

**Comment by jonfroehlich** [comment]
It's back!

![image](https://user-images.githubusercontent.com/1621749/46238079-d04e1680-c33d-11e8-8deb-4a1f97078ec6.png)
