### ISSUE TITLE
Received Server 500 Error when trying to upload a Publication

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#601]
Found this while trying to resolve #578.

**Comment by jonfroehlich** [comment]
@aileenzeng, what's the status of this? I believe you met with Jason and resolved this, right?

**Comment by aileenzeng** [comment]
@jonfroehlich I got this error after my meeting with Jason, so I’m not quite sure! We also talked about different errors during our meeting (primarily: CSS not loading on admin site, splitting up production and test databases), so this may be a new issue.

**Comment by jonfroehlich** [comment]
I haven't seen this occur recently, so closing for now.
