### ISSUE TITLE
Filter bar scrolling is broken

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#631]
I'm here:
![image](https://user-images.githubusercontent.com/1621749/46509357-12240480-c7f7-11e8-93f9-1bc489888da8.png)

and then I scroll down a bit and filter bar starts scrolling up! that's not what we want. some recent PR must have created this bug :(

![image](https://user-images.githubusercontent.com/1621749/46509383-2ec03c80-c7f7-11e8-965a-47ef8dc463e8.png)

![image](https://user-images.githubusercontent.com/1621749/46509391-3a136800-c7f7-11e8-88ae-951b341ec9b3.png)

**Comment by htadeusiak** [comment]
Can I close this issue?

**Comment by jonfroehlich** [comment]
Yep!
