### ISSUE TITLE
Fix top of member.html

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#694]
Lots of things wrong:

- [x] Remove banner
- [x] When at top of page in non-scroll position, make menu bar white, text black, and ml logo black
- [x] Change all icons (e.g., twitter, mail icon) to be black
- [x] Fix web link icon so that it's not showing the little text at the bottom or find a different icon to use
- [ ] I don't like how the bio information is shown. What to do with this? Just in general this whole headshot -> name + links -> bio feels weird in its layout and design

![image](https://user-images.githubusercontent.com/1621749/48382039-f92f2e80-e693-11e8-9f00-e681142114fc.png)

**Comment by htadeusiak** [comment]
@jonfroehlich What about this for the layout of the bio information?

<img width="1440" alt="screen shot 2018-12-15 at 1 34 28 pm" src="https://user-images.githubusercontent.com/33988444/50047635-352c2980-006e-11e9-90b1-b8296305e5c8.png">

**Comment by jonfroehlich** [comment]
Can you mock up 5-10 ideas and then post them. You can use PowerPoint, Keynote, or a tool of your preference for the mocks. 

Also might help to do some background design research (i.e., how do others layout a headshot with links + bio).

**Comment by htadeusiak** [comment]
Here is what I found so far. I'm not too stoked on anything yet, so I'm going to keep looking. But let me know if anything seems to be appealing to you.

[Member Page Design Research.pdf](https://github.com/jonfroehlich/makeabilitylabwebsite/files/2697470/Member.Page.Design.Research.pdf)

**Comment by jonfroehlich** [comment]
Thanks for conducting this preliminary design research. I agree that you haven't yet found an appealing solution. I suppose I like this one best:

![image](https://user-images.githubusercontent.com/1621749/50283993-9add3480-0425-11e9-95f4-0a945de7e954.png)

Unless we find a much better solution, I think we might be able to get away with slight modifications to the current design:

![image](https://user-images.githubusercontent.com/1621749/50284042-bfd1a780-0425-11e9-91cf-b1b14e5efef6.png)

I would suggest removing the vertical bar, standardizing the icons (should be all black) with better vertical spacing (using Gestalt groupings), etc.

But keep working on both conducting design research and rapidly creating some mocks that we can review! :)

**Comment by htadeusiak** [comment]
How does this look for the white nav bar? I had it fade into the regular black nav bar. Is that what you were looking for? Or did you want it to fade into another color?

![personpage](https://user-images.githubusercontent.com/33988444/50437627-6b07b400-089f-11e9-8cf0-f71dacf3c804.gif)

**Comment by htadeusiak** [comment]
Yes, I believe I fixed that issue in another one of my PRs.

**Comment by jonfroehlich** [comment]
ok!

**Comment by htadeusiak** [comment]
Would it be alright if I push what I have and open a new issue for the member page design?

**Comment by jonfroehlich** [comment]
Yep!
