### ISSUE TITLE
Too much space between project thumbnail and label on member page

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#704]
@htadeusiak fixed https://github.com/jonfroehlich/makeabilitylabwebsite/issues/670 but now I noticed that there is too much vertical space between the project thumbnail and label on the member page. Note that because this code is responsive and the thumbnails auto-resize based on window width, this vertical distance is variable.

![image](https://user-images.githubusercontent.com/1621749/50284373-daf0e700-0426-11e9-91b7-d0b81d68641e.png)

**Comment by htadeusiak** [comment]
How does this look?

<img width="1325" alt="screen shot 2018-12-20 at 11 55 48 am" src="https://user-images.githubusercontent.com/33988444/50307841-54500000-044e-11e9-9d6f-2232c9433446.png">

**Comment by jonfroehlich** [comment]
Better! But to be sure I need to see a direct before and after. Also need to see multiple screenshots for different window widths since the Html/css is responsive.

**Comment by htadeusiak** [comment]
1. Before:
<img width="1301" alt="screen shot 2018-12-20 at 12 04 12 pm" src="https://user-images.githubusercontent.com/33988444/50308201-6a11f500-044f-11e9-8582-1c3a1a8c7517.png">
1. After:
<img width="1325" alt="screen shot 2018-12-20 at 11 55 48 am" src="https://user-images.githubusercontent.com/33988444/50308209-6ed6a900-044f-11e9-90aa-bbd3d6cd71ff.png">

2. Before:
<img width="1166" alt="screen shot 2018-12-20 at 12 05 10 pm" src="https://user-images.githubusercontent.com/33988444/50308240-8746c380-044f-11e9-833e-29ba59eeeb8d.png">
2. After:
<img width="1065" alt="screen shot 2018-12-20 at 12 09 52 pm" src="https://user-images.githubusercontent.com/33988444/50308472-2ec3f600-0450-11e9-81f0-4ab50103858f.png">

3. Before:
<img width="867" alt="screen shot 2018-12-20 at 12 06 04 pm" src="https://user-images.githubusercontent.com/33988444/50308390-e99fc400-044f-11e9-9920-6aeaa963bd24.png">
3. After:
<img width="919" alt="screen shot 2018-12-20 at 12 10 33 pm" src="https://user-images.githubusercontent.com/33988444/50308537-6337b200-0450-11e9-88c3-8f275c7d5715.png">

4. Before:
<img width="431" alt="screen shot 2018-12-20 at 12 08 51 pm" src="https://user-images.githubusercontent.com/33988444/50308443-105dfa80-0450-11e9-9d28-243242db50ca.png">
4. After:
<img width="428" alt="screen shot 2018-12-20 at 12 11 14 pm" src="https://user-images.githubusercontent.com/33988444/50308540-659a0c00-0450-11e9-8891-1e954cc61ba7.png">

**Comment by jonfroehlich** [comment]
Looks great. You can merge this PR.
