### ISSUE TITLE
Find a rich text editor plugin for Django

### ISSUE THREAD

**Issue by htadeusiak** [jonfroehlich/makeabilitylabwebsite#706]
Need to find a rich text editor plugin for Django. We are adding a FAQ page and want to add/edit content of this page via the Django admin interface.

**Comment by jonfroehlich** [comment]
We also want a rich editor plugin for news entries, etc. I believe we already have an issue for this but it should be linked explicitly.

**Comment by htadeusiak** [comment]
#35

**Comment by jonfroehlich** [comment]
Gonna close this because redundant with https://github.com/jonfroehlich/makeabilitylabwebsite/issues/35
