### ISSUE TITLE
Add new students

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#717]
For 'Current Team'

- [x] Tadashi Grindeland (non-visual ui dev with Venkatesh)
- [x] Lukas Strobel (Project Sidewalk)
- [x] Paari Gopal (Project Sidewalk)
- [x] Marianne Aubin Le Quere (Project Sidewalk)
- [x] Hank Tadeusiak (website dev)
- [x] Ather Sharif (temporal tracking urban accessibility)

For 'Collaborators'
- [x] Galen Weld (Project Sidewalk)
- [x] Esther Jang (Project Sidewalk)

**Comment by htadeusiak** [comment]
Is Marianne Aubin Le Quere a PHD Student? I just uploaded her to the website if you would like to take a look and make sure I'm doing it correctly.

**Comment by jonfroehlich** [comment]
MS student in HCDE.

**Comment by htadeusiak** [comment]
Correct me if I'm wrong, but for Ather I don't see a temporal tracking project in the database. For now I uploaded him with just Project Sidewalk. 

<img width="325" alt="screen shot 2019-01-11 at 12 33 41 pm" src="https://user-images.githubusercontent.com/33988444/51058307-37b26e00-159d-11e9-9633-743a5f2bc381.png">

**Comment by jonfroehlich** [comment]
Urban Accessibility Evolution.

**Comment by htadeusiak** [comment]
On it
