### ISSUE TITLE
At some window widths, ML logo in menubar has no left margin

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#720]
At some window widths, the ML logo has no left margin so it's pressed up exactly against left side of window. This should not happen.

![image](https://user-images.githubusercontent.com/1621749/50617995-df94b100-0ea4-11e9-926f-4545e6a36055.png)

**Comment by jonfroehlich** [comment]
This might be because I was running the `adding-import-commands` branch...

**Comment by htadeusiak** [comment]
I would like to get this merged before I look at the double line issue. Also slight change in the text of the logo, I don't know if you would like to open another issue for this.
![resize](https://user-images.githubusercontent.com/33988444/50817065-77483400-12d7-11e9-8085-65024fdf559d.gif)

**Comment by jonfroehlich** [comment]
I merged this... but the Issue is still open. Is there work remaining?

**Comment by htadeusiak** [comment]
It's been doing this lately, I'm not sure why. But even after you merge, it doesn't automatically close the issue. There are another couple issues that have been merged but not closed.

But no, there is no work remaining. I'll close it now.
