### ISSUE TITLE
At some window widths, menubar drops to two lines

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#721]
This should not happen. Menu bar should either be a single line or collapse to hamburger menu.

![image](https://user-images.githubusercontent.com/1621749/50618027-0eab2280-0ea5-11e9-852f-f94f663838fb.png)

**Comment by jonfroehlich** [comment]
This might be because I was running the `adding-import-commands` branch...

**Comment by jonfroehlich** [comment]
@htadeusiak, are you on this? You worked on something related...

**Comment by htadeusiak** [comment]
Ill get this done today
