### ISSUE TITLE
Left align all top level headers in the sidebar menu with the FAQ text in the gray box

### ISSUE THREAD

**Issue by htadeusiak** [jonfroehlich/makeabilitylabwebsite#726]
Left align all top level headers in the sidebar menu with the FAQ text in the gray box. That is, remove the indentation.

**Comment by htadeusiak** [comment]
Before:
<img width="1440" alt="screen shot 2019-01-03 at 6 13 55 pm" src="https://user-images.githubusercontent.com/33988444/50670926-64ee9300-0f83-11e9-9afc-633c9cd606bf.png">
After:
<img width="1440" alt="screen shot 2019-01-03 at 6 14 44 pm" src="https://user-images.githubusercontent.com/33988444/50670939-7f287100-0f83-11e9-899a-45ab797c71f7.png">

Is this what you wanted?

**Comment by jonfroehlich** [comment]
Yes! Nice job!
