### ISSUE TITLE
Can the FAQ menu float on the side just like the pubs sidebar?

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#737]
![image](https://user-images.githubusercontent.com/1621749/50710540-1e02ab00-1020-11e9-883a-80ea3ada52fb.png)

@htadeusiak, thoughts?

**Comment by htadeusiak** [comment]
Yes we can do this. The only issue I see is if you make the questions list too long, the user will not be able to click/see some of the questions below the visible window. Does that make sense?

**Comment by jonfroehlich** [comment]
Doh, you’re right. Not a good idea! :) let’s close this Issue.
