### ISSUE TITLE
Show links beneath talks only on hover

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#738]
The small links below talks should only be visible on mouse hover (over any part of the div related to that talk)

![image](https://user-images.githubusercontent.com/1621749/50715318-9cb41400-1031-11e9-9cfd-b7042323f01f.png)

**Comment by jonfroehlich** [comment]
This doesn't seem to be working on the landing page (arguably the most important page on the website).

**Comment by htadeusiak** [comment]
This is fixed in pr #744 I believe

**Comment by jonfroehlich** [comment]
OK, I'll need to check it. I missed that PR.
