### ISSUE TITLE
At some widths the Makeability Lab logo it not vertically centered

### ISSUE THREAD

**Issue by htadeusiak** [jonfroehlich/makeabilitylabwebsite#745]
![screen shot 2019-01-07 at 11 34 57 pm](https://user-images.githubusercontent.com/33988444/50816308-01db6400-12d5-11e9-8d6c-38a020c0128e.png)

**Comment by jonfroehlich** [comment]
Good catch. I noticed this on mobile too.

**Comment by jonfroehlich** [comment]
![image](https://user-images.githubusercontent.com/1621749/50851217-046ba700-1331-11e9-93fc-823b030ecf17.png)
