### ISSUE TITLE
Paper titles should be hyperlinked on pubs

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#749]
Paper titles should be hyperlinked on pubs but the visual look should stay the same (i.e., titles should not be underlined or look blue)

![image](https://user-images.githubusercontent.com/1621749/50988413-61966280-14c1-11e9-81f3-bcbdc90fc426.png)

**Comment by htadeusiak** [comment]
On hover should they become underlined? It does this on the homepage already.
