### ISSUE TITLE
HCDE department and extra space after member title bugs

### ISSUE THREAD

**Issue by htadeusiak** [jonfroehlich/makeabilitylabwebsite#756]
You can see Marianne is a HCDE student. However, when you dive into her page it only displays the letter H for her major. 

There is also an added space after the member's title and before the comma.

- [x] Fix HCDE bug
- [x] Remove added space after member title and department

HCDE Bug:
![screen shot 2019-01-14 at 10 17 18 pm](https://user-images.githubusercontent.com/33988444/51162280-7d479300-184a-11e9-8191-b6cfeaaa1a95.png)
![screen shot 2019-01-14 at 10 18 38 pm](https://user-images.githubusercontent.com/33988444/51162282-7e78c000-184a-11e9-8a2e-d747ff3cd727.png)
Added space bug:
![screen shot 2019-01-14 at 10 28 48 pm](https://user-images.githubusercontent.com/33988444/51162668-e11e8b80-184b-11e9-91c3-e3403b9ed2ff.png)

**Comment by jonfroehlich** [comment]
Also, her content on people page is one line too long due to length of name. Need a solution.

**Comment by htadeusiak** [comment]
I think we make the font slightly smaller so it fits on one line.

**Comment by jonfroehlich** [comment]
Hahah. Ok. Let’s try it. Maybe make the other text beneath the name slightly smaller as well?
