### ISSUE TITLE
Banner images for smarthome dhh project are low res

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#762]
I couldn't find the original high-level images so just grabbed a few for now. Need to be replaced by their hi-res counterparts:

![image](https://user-images.githubusercontent.com/1621749/51368498-892e9180-1aa4-11e9-8623-89c7ab36644d.png)

**Comment by jonfroehlich** [comment]
@higherdefender, can you do this?

**Comment by higherdefender** [comment]
Yep, done! I will update photos once more after we make the video as well.
