### ISSUE TITLE
Makes news headline and news image clickable

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#791]
On the News page (https://makeabilitylab.cs.washington.edu/news/), the news headline and news image should be clickable (and should take you to the story).

![image](https://user-images.githubusercontent.com/1621749/53772308-ce632300-3e9a-11e9-92b5-651ab64562ca.png)

**Comment by htadeusiak** [comment]
If you would like to take a look at this one on the test website and let me know if it looks good

**Comment by jonfroehlich** [comment]
I think it looks good. Thanks.
