### ISSUE TITLE
Publications and awards: personal author images don't show the award overlay as the central publication page

### ISSUE THREAD

**Issue by manaswis** [jonfroehlich/makeabilitylabwebsite#797]
Main publication page:

![image](https://user-images.githubusercontent.com/2873216/54622715-44cd5c80-4a27-11e9-9238-9ccdb1b62bf5.png)

Publications on author page:

![image](https://user-images.githubusercontent.com/2873216/54622747-57479600-4a27-11e9-8802-f89a4983a144.png)

**Comment by jonfroehlich** [comment]
Thanks @manaswis. I was aware of this one but I see that it's not encoded as an Issue yet. Thanks for adding it.

**Comment by jonfroehlich** [comment]
Also an issue for project pages:

https://makeabilitylab.cs.washington.edu/project/anchoredaudiosampling/

**Comment by jonfroehlich** [comment]
Deployed on test server.
