### ISSUE TITLE
Tool-tip needed for adding positions when people

### ISSUE THREAD

**Issue by johnsonkuang** [jonfroehlich/makeabilitylabwebsite#809]
Small issue found during testing. When adding a new person, the developer must also add a position. Example shown below:

### When trying to add person
Console
`web_1  | PositionInline.formfield_for_foreignkey: db_field: website.Position.grad_mentor db_field.name grad_mentor request: <WSGIRequest: POST '/admin/website/person/add/?_to_field=id&_popup=1'>` 

[![Image from Gyazo](https://i.gyazo.com/bb0e64119835bd18d602acdd663e80df.png)](https://gyazo.com/bb0e64119835bd18d602acdd663e80df)

As far as I've seen, this issue has only applied to cases where you add people from another model. When you try to use that created person, it is not valid.

**Comment by jonfroehlich** [comment]
Can you update the title to this Issue so that it is more understandable?

**Comment by jonfroehlich** [comment]
@johnsonkuang, I still don't understand this Issue and the title of 'Tool-tip needed for adding positions when people' doesn't make sense. When people what?
