### ISSUE TITLE
Hidden project shows up on people's personal page

### ISSUE THREAD

**Issue by EdigaHe** [jonfroehlich/makeabilitylabwebsite#841]
The unpublished projects show up on people's personal page. For example, the screenshot shows that kinetic fab study project appears on Jessica's personal page.

![Screen Shot 2019-12-04 at 12 55 35 PM](https://user-images.githubusercontent.com/3831526/70190834-e2e37e80-16ab-11ea-8ada-ec72cdbd71b0.png)

**Comment by jonfroehlich** [comment]
Somewhat related to https://github.com/jonfroehlich/makeabilitylabwebsite/issues/833

Can solve both of them at same time.

**Comment by jonfroehlich** [comment]
Fixed.

https://makeabilitylab.cs.washington.edu/member/jessicachin/

![image](https://user-images.githubusercontent.com/1621749/70247703-a86ef580-172e-11ea-9897-86fe13b1bed9.png)
